# Generated by Terraform - DO NOT EDIT

source ~/.profile-env
source ~/.profile-alias
source ~/.profile-function

[[ -f ~/.profile.local ]] && source ~/.profile.local
[[ -f ~/.profile-env.local ]] && source ~/.profile-env.local
[[ -f ~/.profile-alias.local ]] && source ~/.profile-alias.local
[[ -f ~/.profile-function.local ]] && source ~/.profile-function.local

